### PR TITLE
implemented email/pw login feature

### PR DESCRIPTION
**Pull request by vladtdr1**

### CODE REVIEW

**Review by Alexandra2612 — CHANGES_REQUESTED** [review]
Please split the login functionality into the three packages to match the architecture

**Comment by vladtdr1** [comment]
> Please split the login functionality into the three packages to match the architecture

no

**Comment by vladtdr1** [comment]
> Please split the login functionality into the three packages to match the architecture

make me

**Review by Alexandra2612 — APPROVED** [review]
Ok! :100:

**Pull request merged**
